// Authentication
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REGISTER_USER_START = 'AUTH_REGISTER_USER_START';
export const AUTH_REGISTER_USER_FAIL = 'AUTH_REGISTER_USER_FAIL';
export const SET_MAIN_USER_START = 'SET_MAIN_USER';
export const SET_MAIN_USER_SUCCESS = 'SET_MAIN_USER_SUCCESS';
// User Management
export const FETCH_USER_INIT = 'FETCH_USER_INIT';
export const FETCH_USER_START = 'FECTH_USER_START';
export const FETCH_USER_SUCCESS = 'FECTH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FECTH_USER_FAIL';
export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
// UserPaging
export const FETCH_USERS_INIT = 'FETCH_USERS_INIT';
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
// Photo Management
export const ADD_PHOTO_TO_USER_START = 'ADD_PHOTO_TO_USER_START';
export const ADD_PHOTO_TO_USER_SUCCESS = 'ADD_PHOTO_TO_USER_SUCCESS';
export const ADD_PHOTO_TO_USER_FAIL = 'ADD_PHOTO_TO_USER_FAIL';
export const DELETE_USER_PHOTO_START = 'DELETE_USER_PHOTO_START';
export const DELETE_USER_PHOTO_SUCCESS = 'DELETE_USER_PHOTO_SUCCESS';
export const DELETE_USER_PHOTO_FAIL = 'DELETE_USER_PHOTO_FAIL';
export const SET_MAIN_PHOTO_START = 'SET_MAIN_PHOTO_START';
export const SET_MAIN_PHOTO_SUCCESS = 'SET_MAIN_PHOTO_SUCCESS';
export const SET_MAIN_PHOTO_FAIL = 'SET_MAIN_PHOTO_FAIL';
//Activity Managemente
export const FETCH_ACTIVITY_INIT = 'FETCH_ACTIVITY_INIT';
export const FETCH_ACTIVITY_START = 'FECTH_ACTIVITY_START';
export const FETCH_ACTIVITY_SUCCESS = 'FECTH_ACTIVITY_SUCCESS';
export const FETCH_ACTIVITY_FAIL = 'FECTH_ACTIVITY_FAIL';
export const UPDATE_ACTIVITY_START = 'UPDATE_ACTIVITY_START';
export const UPDATE_ACTIVITY_SUCCESS = 'UPDATE_ACTIVITY_SUCCESS';
export const UPDATE_ACTIVITY_FAIL = 'UPDATE_ACTIVITY_FAIL';
// ActivityPaging
export const FETCH_ACTIVITIES_INIT = 'FETCH_ACTIVITIES_INIT';
export const FETCH_ACTIVITIES_START = 'FETCH_ACTIVITIES_START';
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS';
export const FETCH_ACTIVITIES_FAIL = 'FETCH_ACTIVITIES_FAIL';


export const ADD_ACTIVITY_START = 'ADD_ACTIVITY_START';
export const ADD_ACTIVITY_SUCCESS = 'ADD_ACTIVITY_SUCCESS';
export const ADD_ACTIVITY_FAIL = 'ADD_ACTIVITY_FAIL';


export const DELETE_ACTIVITY_START = 'DELETE_ACTIVITY_START';
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS';
export const DELETE_ACTIVITY_FAIL = 'DELETE_ACTIVITY_FAIL';